### ISSUE TITLE
Authentication token is missing or invalid

### ISSUE THREAD

**Issue by siaimes** [microsoft/openpaimarketplace#325]
I used the following docker-compose to deploy the marketplace on the DMZ host.

```
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License
version: "3"
services:

  marketplace-db:
    container_name: marketplace-db
    image: openpai/marketplace-db:${TAG}
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: marketplace
      POSTGRES_DB: marketplace
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  marketplace-restserver:
    container_name: marketplace-restserver
    image: openpai/pai-marketplace-restserver:${TAG}
    restart: always
    depends_on:
      - marketplace-db
    environment:
      DB_USERNAME: user
      DATABASE: marketplace
      DB_PASSWORD: marketplace
      DB_HOST: marketplace-db
      DB_PORT: 5432
      PORT: 9293

  marketplace-webportal:
    container_name: marketplace-webportal
    image: openpai/pai-marketplace-webportal:${TAG}
    restart: always
    environment:
      MARKETPLACE_API_URL: https://my-domain/pai-marketplace/api

  marketplace-nginx:
    restart: always
    container_name: marketplace-nginx
    image: nginx
    volumes:
      - ./nginx/conf/conf.d:/etc/nginx/conf.d
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx
```

`TAG=v1.8.0`, and the configuration of Nginx is shown below.

```
server {
    ...

    location /pai-marketplace/ {
        proxy_pass http://marketplace-webportal:9292/;
    }

    location /pai-marketplace/api/ {
        proxy_pass http://marketplace-restserver:9293/;
    }

    ...

}
```

Then I can access plugin.js and rest server API through the following link:
```
https://my-domain/pai-marketplace/plugin.js
https://my-domain/pai-marketplace/api/
```

Then I configured openpai as follows according to the document:

```
culster.common.marketplace=true
```

```
webportal:
  server-port: 9286
  marketplace: false
  save-template: true
  plugins:
  - id: marketplace
    title: Marketplace
    uri: https://my-domain/pai-marketplace/plugin.js
```

However, the browser prompts me with `Internal Server Error`.

From the browser's console, we can see that the following two links will encounter `500 Internal Server Error Error`.

```
https://my-domain/pai-marketplace/api/categories
https://my-domain/pai-marketplace/api/items?type=all
```
When I visit the link directly, it prompts me `Authentication token is missing or invalid`.

Why does this issue occur? How to solve it?
